version: '3.8'

services:
  fastapi:
    build: .
    volumes:
      - ./uploaded_files:/app/uploaded_files
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./uploaded_files:/app/uploaded_files
    ports:
      - '777:777'
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
